//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkogsCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lumbermill
    {
        public string organizationNbr { get; set; }
        public string address { get; set; }
        public string capacity { get; set; }
        public string coordinates { get; set; }
    
        public virtual ForestEstate ForestEstate { get; set; }
    }
}
