//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkogsCRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkogsDBEntities : DbContext
    {
        public SkogsDBEntities()
            : base("name=SkogsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Estate> Estate { get; set; }
        public virtual DbSet<ForestEstate> ForestEstate { get; set; }
        public virtual DbSet<Lumbermill> Lumbermill { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<SalesAgent> SalesAgent { get; set; }
    }
}
