//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkogsCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int quantity { get; set; }
        public int orderId { get; set; }
        public string coordinates { get; set; }
    
        public virtual ForestEstate ForestEstate { get; set; }
    }
}
